[
 {
  "author": "andy", 
  "date": "2011-11-22T17:49:21.427370Z", 
  "msg": [], 
  "revision_id": "1205110"
 }, 
 {
  "author": "pamarcelot", 
  "date": "2011-11-22T17:49:04.911639Z", 
  "msg": [
   "Added files to svn:ignore."
  ], 
  "revision_id": "1205109"
 }, 
 {
  "author": "pamarcelot", 
  "date": "2011-11-22T17:48:45.035972Z", 
  "msg": [
   "Added files to svn:ignore."
  ], 
  "revision_id": "1205108"
 }, 
 {
  "author": "hughesj", 
  "date": "2011-11-22T17:47:14.861898Z", 
  "msg": [
   "Clarify a few points made here: http://mail-archives.apache.org/mod_mbox/aries-dev/201103.mbox/%3C1300364661.27234.33.camel%40meschbix%3E"
  ], 
  "revision_id": "1205107"
 }, 
 {
  "author": "dblevins", 
  "date": "2011-11-22T17:47:13.030898Z", 
  "msg": [
   "Since this version of EJBException effectively holds two causes (getCause() and the legacy getCausedByException())", 
   "updated getCause(), getMessage(), and printStackTrace() methods to be sensitive of when the two causes are the same."
  ], 
  "revision_id": "1205106"
 }
]