[
 {
  "author": "rmuir", 
  "date": "2012-09-30T16:12:08.425855Z", 
  "msg": [
   "LUCENE-4453: test BlockPostings special cases"
  ], 
  "revision_id": "1392058"
 }, 
 {
  "author": "rmuir", 
  "date": "2012-09-30T16:08:49.899310Z", 
  "msg": [
   "LUCENE-4453: test BlockPostings special cases"
  ], 
  "revision_id": "1392057"
 }, 
 {
  "author": "rdonch", 
  "date": "2012-09-30T16:07:38.735820Z", 
  "msg": [
   "* subversion/bindings/swig/python/libsvn_swig_py/swigutil_py.c:", 
   "(svn_swig_py_config_enumerator2): Always clear the Python exception", 
   "to avoid leaving Python in an inconsistent exception state."
  ], 
  "revision_id": "1392056"
 }, 
 {
  "author": "acmurthy", 
  "date": "2012-09-30T15:55:29.182068Z", 
  "msg": [
   "hadoop-2.0.2-alpha rc1"
  ], 
  "revision_id": "1392055"
 }, 
 {
  "author": "acmurthy", 
  "date": "2012-09-30T15:54:51.701756Z", 
  "msg": [
   "Re-spin hadoop-2.0.2-alpha-rc1"
  ], 
  "revision_id": "1392054"
 }
]