[
 {
  "author": "chug", 
  "date": "2013-03-27T19:24:13.893642Z", 
  "msg": [
   "QPID-4631 create link lockdown - fix sasl_fed test"
  ], 
  "revision_id": "1461813"
 }, 
 {
  "author": "fmeschbe", 
  "date": "2013-03-27T19:24:05.619163Z", 
  "msg": [
   "Formatting and import organizations"
  ], 
  "revision_id": "1461812"
 }, 
 {
  "author": "jwross", 
  "date": "2013-03-27T19:23:50.177341Z", 
  "msg": [
   "[ARIES-1041] Change dependency on org.apache.aries.subsystem.api from 1.0.0-SNAPSHOT to 1.0.0."
  ], 
  "revision_id": "1461811"
 }, 
 {
  "author": "neels", 
  "date": "2013-03-27T19:22:57.619096Z", 
  "msg": [
   "Cosmetic.", 
   "* subversion/libsvn_repos/commit.c", 
   "(check_cntrl): Rename to...", 
   "(check_valid_path): ...this.", 
   "(add_file_or_directory): Move comment to function check_valid_path()."
  ], 
  "revision_id": "1461810"
 }, 
 {
  "author": "julianfoad", 
  "date": "2013-03-27T19:17:27.910227Z", 
  "msg": [
   "* subversion/tests/cmdline/svntest/main.py", 
   "(run_command_stdin): Report the command and its exit code when raising an", 
   "exception due to unexpected exit code or stderr, as the plain 'Failure'", 
   "exception was giving no clue about what was failing."
  ], 
  "revision_id": "1461809"
 }
]