[
 {
  "author": "cziegeler", 
  "date": "2013-08-13T07:08:16.289396Z", 
  "msg": [
   "Use released version as dependency"
  ], 
  "revision_id": "1513373"
 }, 
 {
  "author": "cziegeler", 
  "date": "2013-08-13T07:07:45.592934Z", 
  "msg": [
   "Use released version for testing"
  ], 
  "revision_id": "1513372"
 }, 
 {
  "author": "ningjiang", 
  "date": "2013-08-13T07:07:05.573439Z", 
  "msg": [
   "Merged revisions 1513076 via svnmerge from", 
   "https://svn.apache.org/repos/asf/cxf/trunk", 
   "........", 
   "r1513076 | ningjiang | 2013-08-12 16:35:06 +0800 (Mon, 12 Aug 2013) | 1 line", 
   "CXF-5196 fixed the issue that Failover feature doesn't work when client uses async invocation", 
   "........"
  ], 
  "revision_id": "1513371"
 }, 
 {
  "author": "kayyagari", 
  "date": "2013-08-13T07:06:37.849072Z", 
  "msg": [
   "removed test code"
  ], 
  "revision_id": "1513370"
 }, 
 {
  "author": "mduerig", 
  "date": "2013-08-13T07:06:31.442973Z", 
  "msg": [
   "OAK-957: SQL2NodeLocalNameTest test failures", 
   "temporarily disable failing tests"
  ], 
  "revision_id": "1513369"
 }
]