[
 {
  "author": "amyroh", 
  "date": "2002-08-16T21:05:16.000000Z", 
  "msg": [
   "Update the doc following the current DBCP implementation - \"username\" instead of \"user\"."
  ], 
  "revision_id": "301159"
 }, 
 {
  "author": "amyroh", 
  "date": "2002-08-16T21:04:26.000000Z", 
  "msg": [
   "Update the JNDI datasource sample configuration following the current DBCP", 
   "implementation - \"username\" instead of \"user\"."
  ], 
  "revision_id": "301158"
 }, 
 {
  "author": "amyroh", 
  "date": "2002-08-16T19:00:35.000000Z", 
  "msg": [
   "Add error messages for JNDIRealm."
  ], 
  "revision_id": "301157"
 }, 
 {
  "author": "patrickl", 
  "date": "2002-08-16T18:51:20.000000Z", 
  "msg": [
   "This patch fixes the JUnit tests in Catalina to run against the ROOT webapp. Now 'ant test' succeeds.", 
   "Submitted by:\tSteve Downey (steve.downey@netfolio.com)"
  ], 
  "revision_id": "301156"
 }, 
 {
  "author": "patrickl", 
  "date": "2002-08-15T19:11:31.000000Z", 
  "msg": [
   "If a Servlet generates a RuntimeException, it is wrapped by a ServletException.  Since there is an entry for ServletException in the web.xml, the actual root cause (in this case, an IllegalStateException) was never unwrapped, thus leading to unexpected behavior.", 
   "I made a simple modification to the logic so that if the throwable passed to the ErrorDispatcherValve is a ServletException, it will attempt to get the root cause.  If the root cause is null, then proceed with the error page lookup with the ServletException as the throwable object, otherwise, use the root cause for the error page lookup.", 
   "Submitted by:\tRyan Lubke (ryan.lubke@sun.com)"
  ], 
  "revision_id": "301155"
 }
]