[
 {
  "author": "aheritier", 
  "date": "2006-02-23T00:05:52.605305Z", 
  "msg": [
   "fix another bad copy/paste"
  ], 
  "revision_id": "379995"
 }, 
 {
  "author": "aheritier", 
  "date": "2006-02-23T00:00:22.212397Z", 
  "msg": [
   "fix a bad copy/paste"
  ], 
  "revision_id": "379994"
 }, 
 {
  "author": "kmarsden", 
  "date": "2006-02-22T23:57:30.313608Z", 
  "msg": [
   "DERBY-1010 - setTransactionIsolation can cause ava.sql.SQLException: Invalid operation: statement closed in some contexts with xa", 
   "Client has a Statement object that it reuses to send SET CURRENT ISOLATION commands to the server.  Added a check to make sure this statement was not closed before trying to reuse it.", 
   "This change takes the checkDataSource test a bit further (DERBY-435) but there seem to be issues with isolation being set correctly with xa_join.  I will investigate that and file a Jira issue"
  ], 
  "revision_id": "379993"
 }, 
 {
  "author": "aheritier", 
  "date": "2006-02-22T23:55:52.712800Z", 
  "msg": [
   "add the issue number for MPCHANGES-25"
  ], 
  "revision_id": "379992"
 }, 
 {
  "author": "clr", 
  "date": "2006-02-22T23:54:36.802838Z", 
  "msg": [
   "Create 2.0-rc1 branch"
  ], 
  "revision_id": "379991"
 }
]