[
 {
  "author": "lundblad", 
  "date": "2007-02-22T22:24:31.678262Z", 
  "msg": [
   "Merge r21453 and r23468 to the 1.4.x-r23468 branch."
  ], 
  "revision_id": "863545"
 }, 
 {
  "author": "dlr", 
  "date": "2007-02-22T22:20:53.560896Z", 
  "msg": [
   "* www/merge-tracking/requirements.html", 
   "Link index sections to internal page anchors.  Further compress", 
   "links from the \"Audit\" section into broader categories.  Re-organize", 
   "the \"Audit\" section, creating three sub-sections."
  ], 
  "revision_id": "863544"
 }, 
 {
  "author": "lundblad", 
  "date": "2007-02-22T21:51:21.804923Z", 
  "msg": [
   "* /branches/1.4.x-r23468: Create backport branch."
  ], 
  "revision_id": "863543"
 }, 
 {
  "author": "lundblad", 
  "date": "2007-02-22T21:42:19.203392Z", 
  "msg": [
   "Fix regression introduced in r21720: update of a replaced file *without*", 
   "history uses the revert-base.  Only replaced files *with* history have a", 
   "revert-base.", 
   "* subversion/libsvn_wc/update_editor.c", 
   "(apply_textdelta, merge_file): Only use revert-base for", 
   "replaced-with-history files.", 
   "* subversion/tests/cmdline/update_tests.py", 
   "(update_wc_with_replaced_file): Extend with a test with a file replaced", 
   "without history."
  ], 
  "revision_id": "863542"
 }, 
 {
  "author": "malcolm", 
  "date": "2007-02-22T21:29:44.943539Z", 
  "msg": [
   "Fix part of issue 2692: allow clients to checkout unknown special file", 
   "types as regular files with the svn:special property set (like symlinks", 
   "on Windows), instead of treating an unknown special file type as a fatal", 
   "error (which, since we don't validate the type on commit, allows one", 
   "client to DoS all the others).", 
   "This incidentally also fixes special_tests test 8, since the error there", 
   "is caused by the same problem.", 
   "Review by: lundblad", 
   "* subversion/libsvn_subr/subst.c", 
   "(create_special_file_from_stringbuf): Create a regular file containing", 
   "the special file's internal representation if the special file type", 
   "was unknown, re-using the code for creating 'symlinks' on Windows", 
   "otherwise.", 
   "* subversion/tests/cmdline/special_tests.py", 
   "(checkout_repo_with_unknown_special_type): New.  Check that we can", 
   "check out a repository containing a special file of unknown type.", 
   "(test_list): Unmark merge_file_into_symlink as XFail, and add", 
   "checkout_repo_with_unknown_special_type to test the issue directly.", 
   "* subversion/tests/cmdline/special_tests_data/bad-special-type.dump", 
   "New.  Dumpfile for checkout_repo_with_unknown_special_type."
  ], 
  "revision_id": "863541"
 }
]