[
 {
  "author": "pburba", 
  "date": "2008-03-11T19:41:24.905287Z", 
  "msg": [
   "* STATUS: Nominate r29855."
  ], 
  "revision_id": "869930"
 }, 
 {
  "author": "pburba", 
  "date": "2008-03-11T19:40:59.963294Z", 
  "msg": [
   "Fix a bug in serf's implementation of svn_ra_get_mergeinfo() where empty", 
   "mergeinfo is ignored.", 
   "Note: This fixes the 'x86-macosx-gnu shared daily ra_serf' buildbot's", 
   "long-standing XPASS failure of merge_tests.py 80 merge --reintegrate on a", 
   "never-updated branch.", 
   "* subversion/libsvn_ra_serf/mergeinfo.c", 
   "(end_element): Mergeinfo value of \"\" is valid (i.e. it's empty", 
   "mergeinfo), so don't ignore it."
  ], 
  "revision_id": "869929"
 }, 
 {
  "author": "rocketraman", 
  "date": "2008-03-11T18:50:10.347563Z", 
  "msg": [
   "svnmerge.py: Similar to r29741, fix brokenness with r29666 when there is no", 
   "default locale for sys.stdout.encoding in Python.", 
   "* contrib/client-side/svnmerge/svnmerge.py", 
   "(recode_stdout_to_file): Treat as a no-op when sys.stdout.encoding returns", 
   "None."
  ], 
  "revision_id": "869928"
 }, 
 {
  "author": "glasser", 
  "date": "2008-03-11T18:38:18.885001Z", 
  "msg": [
   "On the in-memory cache branch:", 
   "Stub out cache functions; test now links (but doesn't pass).", 
   "* subversion/libsvn_subr/cache.c", 
   "New.", 
   "* subversion/tests/libsvn_subr", 
   "Add cache-test to svn:ignore."
  ], 
  "revision_id": "869927"
 }, 
 {
  "author": "cmpilato", 
  "date": "2008-03-11T18:19:06.978800Z", 
  "msg": [
   "Add a test for 2-URL merges from foreign repositories.", 
   "(I'm trying to reproduce a scenario I saw earlier today where such a", 
   "merge left wc-props that contained DAV opaque URLs which pointed to", 
   "the wrong repository.  So far, I've not been successful.)", 
   "* subversion/tests/cmdline/merge_tests.py", 
   "(foreign_repos_2_url): New test.", 
   "(test_list): Add references to new test."
  ], 
  "revision_id": "869926"
 }
]