[
 {
  "author": "lgo", 
  "date": "2008-09-14T15:44:20.824489Z", 
  "msg": [
   "Avoid segmentation fault when a revision file has a corrupted changed-path", 
   "item id. This can happen when the id itself is in the wrong format, or the", 
   "offset of the changed-path data is incorrect.", 
   "* subversion/libsvn_fs_fs/fs_fs.c", 
   "(read_change): validate correct noderev_id for the change."
  ], 
  "revision_id": "873145"
 }, 
 {
  "author": "fabien", 
  "date": "2008-09-14T13:41:41.319889Z", 
  "msg": [
   "French translation update for r33069", 
   "* subversion/po/fr.po: po-update & 2 fuzzy fixed"
  ], 
  "revision_id": "873144"
 }, 
 {
  "author": "blair", 
  "date": "2008-09-14T05:48:10.919970Z", 
  "msg": [
   "On the file externals branch.", 
   "* subversion/tests/cmdline/externals_tests.py", 
   "(checkout_with_externals):", 
   "Add some checks on the /A/B/gamma file external."
  ], 
  "revision_id": "873143"
 }, 
 {
  "author": "blair", 
  "date": "2008-09-14T05:33:50.878348Z", 
  "msg": [
   "On the file externals branch.", 
   "Fix exporting of file externals.", 
   "* subversion/libsvn_client/externals.c", 
   "(handle_external_item_change):", 
   "If an export is being done, then use svn_client_export4() to", 
   "export the file instead of using switch_file_external().", 
   "* subversion/tests/cmdline/externals_tests.py", 
   "(test_list):", 
   "Remove the XFail from export_with_externals()."
  ], 
  "revision_id": "873142"
 }, 
 {
  "author": "blair", 
  "date": "2008-09-14T05:28:20.036519Z", 
  "msg": [
   "On the file externals branch.", 
   "* subversion/tests/cmdline/externals_tests.py", 
   "(externals_test_setup):", 
   "Add a file external on the /A/B directory to create a file named", 
   "gamma that is an external to /A/D/gamma using a relative external", 
   "syntax.", 
   "(test_list):", 
   "Mark export_with_externals() as XFail as exporting a file external", 
   "is not supported yet."
  ], 
  "revision_id": "873141"
 }
]