[
 {
  "author": "cmpilato", 
  "date": "2008-11-07T15:38:32.984127Z", 
  "msg": [
   "Minor follow-up to r34082.", 
   "* subversion/mod_dav_svn/mirror.c", 
   "(dav_svn__proxy_merge_fixup): Move a return statement to avoid unnecessary", 
   "processing when a GET or PROPFIND is not proxied through.", 
   "Suggested by: jerenkrantz"
  ], 
  "revision_id": "874170"
 }, 
 {
  "author": "sussman", 
  "date": "2008-11-07T15:25:11.540747Z", 
  "msg": [
   "* subversion/mod_dav_svn/repos.c", 
   "(parse_querystring): use authz_read_func when tracing node locations."
  ], 
  "revision_id": "874169"
 }, 
 {
  "author": "pburba", 
  "date": "2008-11-07T15:07:01.866842Z", 
  "msg": [
   "Follow-up to r34091, adjust expected output in a merge test to work with", 
   "debug builds.", 
   "Suggested by: cmpilato", 
   "* subversion/tests/cmdline/merge_tests.py", 
   "(reintegrate_with_subtree_mergeinfo): Debug builds also output the", 
   "file/lineno of the error, so expect that."
  ], 
  "revision_id": "874168"
 }, 
 {
  "author": "julianfoad", 
  "date": "2008-11-07T14:24:32.558787Z", 
  "msg": [
   "Fix the entries walker again: allow it to walk into a deleted-but-re-added", 
   "directory. This is a follow-up to r34084 which fixed a similar bug but broke", 
   "this case. Also factor out the test used here and in several other places to", 
   "make it easier to keep it consistent.", 
   "* subversion/libsvn_wc/entries.c", 
   "(entry_is_hidden): New function.", 
   "(handle_start_tag, read_entries): Use it. (No functional change.)", 
   "(walker_helper, visit_tc_too_found_entry): Use it, fixing the bug mentioned."
  ], 
  "revision_id": "874167"
 }, 
 {
  "author": "pburba", 
  "date": "2008-11-07T01:29:19.929905Z", 
  "msg": [
   "Delete the reintegrate-improvements branch, it was merged back to trunk."
  ], 
  "revision_id": "874166"
 }
]