[
 {
  "author": "danielsh", 
  "date": "2008-11-07T22:28:47.407432Z", 
  "msg": [
   "Fix issue #3313 by validating all eligible properties (and among them,", 
   "svn:author) for being valid UTF-8.", 
   "* subversion/libsvn_repos/fs-wrap.c", 
   "(validate_prop):", 
   "Apply the \"is UTF-8 and LF\" check whenever svn_prop_needs_translation()", 
   "is true (that is the very definition of the latter)."
  ], 
  "revision_id": "874180"
 }, 
 {
  "author": "kfogel", 
  "date": "2008-11-07T21:43:51.001064Z", 
  "msg": [
   "On the issue-2843-dev branch: bring up-to-date with latest trunk (r34104)."
  ], 
  "revision_id": "874179"
 }, 
 {
  "author": "kfogel", 
  "date": "2008-11-07T21:42:18.185728Z", 
  "msg": [
   "* subversion/tests/cmdline/commit_tests.py", 
   "(test_list): Expect commit_out_of_date_deletions to fail over ra_svn.", 
   "I'm not sure why it wasn't marked this way originally.  See r34101", 
   "and r34073 for more context; I think there was just a multi-way", 
   "confusion here and that it is now un-confused.", 
   "Found by: danielsh", 
   "(He noticed my IRC inquiries and pointed out that ra_svn failure persists.)"
  ], 
  "revision_id": "874178"
 }, 
 {
  "author": "kfogel", 
  "date": "2008-11-07T21:36:06.134139Z", 
  "msg": [
   "On the issue-2843-dev branch:", 
   "* subversion/tests/cmdline/depth_tests.py", 
   "(test_list): Expect excluded_receive_remote_removal to pass now."
  ], 
  "revision_id": "874177"
 }, 
 {
  "author": "kfogel", 
  "date": "2008-11-07T21:34:48.851367Z", 
  "msg": [
   "On the issue-2843-dev branch: bring up-to-date with latest trunk (r34101)."
  ], 
  "revision_id": "874176"
 }
]