[
 {
  "author": "sebb", 
  "date": "2010-05-01T16:04:28.250930Z", 
  "msg": [
   "Unthrown Exceptions"
  ], 
  "revision_id": "940065"
 }, 
 {
  "author": "kkolinko", 
  "date": "2010-05-01T16:00:29.242791Z", 
  "msg": [
   "Log any unexpected errors that might occur during server shutdown from the shutdown hook,", 
   "and do not forget to shutdown (read: flush) the logging subsystem."
  ], 
  "revision_id": "940064"
 }, 
 {
  "author": "sebb", 
  "date": "2010-05-01T15:54:06.199232Z", 
  "msg": [
   "No point catching an Exception only to rethrow it - just let JUnit handle it"
  ], 
  "revision_id": "940063"
 }, 
 {
  "author": "sebb", 
  "date": "2010-05-01T15:50:47.489593Z", 
  "msg": [
   "Avoid possible NPE"
  ], 
  "revision_id": "940062"
 }, 
 {
  "author": "sebb", 
  "date": "2010-05-01T15:47:02.680215Z", 
  "msg": [
   "Unthrown Exceptions"
  ], 
  "revision_id": "940061"
 }
]