[
 {
  "author": "hwright", 
  "date": "2010-07-15T15:53:02.159723Z", 
  "msg": [
   "* subversion/tests/cmdline/basic_tests.py", 
   "(basic_rm_urls_multi_repos): Note that this test is for issue #1199."
  ], 
  "revision_id": "964475"
 }, 
 {
  "author": "philip", 
  "date": "2010-07-15T15:51:25.196111Z", 
  "msg": [
   "* subversion/libsvn_wc/wc_db.c", 
   "(svn_wc__db_temp_forget_directory): Don't unlock if SVN_WC__SINGLE_DB.", 
   "(svn_wc__db_wclock_release): Use correct type for owned_locks."
  ], 
  "revision_id": "964474"
 }, 
 {
  "author": "pburba", 
  "date": "2010-07-15T15:48:50.832517Z", 
  "msg": [
   "* STATUS: Nominate issue #3648 fixes for backport."
  ], 
  "revision_id": "964473"
 }, 
 {
  "author": "pburba", 
  "date": "2010-07-15T15:47:23.314878Z", 
  "msg": [
   "On the 1.6.x-issue3648 branch: Merge r958024, r961055, and r964167 from", 
   "trunk.", 
   "These three revs are the sum of the issue #3648 fixes on trunk.  None of them", 
   "merge cleanly; just about everything that could go wrong did, e.g. tree", 
   "conflicts, text conflicts, new API backports...", 
   "...so I merged all three changes, mostly via subtree merges,", 
   "resolved the numerous conflicts, made the public API private, removed the", 
   "subtree mergeinfo, and finally did a a --record-only merge of the three", 
   "revs to the root to keep things tidy.", 
   "* src-branch-1.6.x-backport", 
   "* CHANGES", 
   "Mergeinfo changes only.", 
   "* subversion/include/private/svn_mergeinfo_private.h", 
   "r961055 added a new public API, svn_mergeinfo_catalog_merge, which we can't", 
   "backport, so instead it is declared here as svn_mergeinfo__catalog_merge.", 
   "* subversion/libsvn_client/merge.c", 
   "Resolved numerous conflicts due to WCNG work on trunk.", 
   "Tweak the doc strings to note the pre-1.7 madness of WC path arguments", 
   "which are either absolute or relative to the current working", 
   "directory...Ugh, how did we ever live with this?! :-)", 
   "* subversion/libsvn_subr/mergeinfo.c", 
   "Clean merge.", 
   "* subversion/tests/cmdline/merge_tests.py", 
   "All three changes added/modified a test in merge_reintegrate_tests.py,", 
   "which doesn't exist on 1.6.x.  So I merged all three directly to", 
   "merge_tests.py.  Also adjusted the call to run_and_verify_merge to work", 
   "properly on 1.6.x (i.e. no expected elision or mergeinfo output, use", 
   "run_and_verify_merge2 to support 2-URL merge)."
  ], 
  "revision_id": "964472"
 }, 
 {
  "author": "philip", 
  "date": "2010-07-15T15:41:32.656419Z", 
  "msg": [
   "Avoid a double unlock.", 
   "* subversion/libsvn_client/update.c", 
   "(internal_update): Don't unlock here, the caller locks and unlocks."
  ], 
  "revision_id": "964471"
 }
]