[
 {
  "author": "sgoeschl", 
  "date": "2010-09-15T19:47:09.048931Z", 
  "msg": [
   "Updating documentation"
  ], 
  "revision_id": "997475"
 }, 
 {
  "author": "cmpilato", 
  "date": "2010-09-15T19:39:04.238215Z", 
  "msg": [
   "For issue #3709 (\"Inconsistency between \"svn list\" and \"svn", 
   "checkout\"), teach svnserve not to transmit unreadable paths in its", 
   "get-dir command response.  I think this completes the fixes for this", 
   "issue.", 
   "* subversion/svnserve/serve.c", 
   "(get_dir): Authorize each child to be returned, omitting those that", 
   "the user isn't allowed to read.", 
   "* subversion/tests/cmdline/authz_tests.py", 
   "(test_list): No longer expect authz_recursive_ls() to fail over ra-svn."
  ], 
  "revision_id": "997474"
 }, 
 {
  "author": "bentmann", 
  "date": "2010-09-15T19:32:40.862718Z", 
  "msg": [
   "o Added Sisu to notice file"
  ], 
  "revision_id": "997473"
 }, 
 {
  "author": "hwright", 
  "date": "2010-09-15T19:32:26.831496Z", 
  "msg": [
   "On the py-tests-as-modules branch:", 
   "Bring up-to-date with trunk."
  ], 
  "revision_id": "997472"
 }, 
 {
  "author": "cmpilato", 
  "date": "2010-09-15T19:27:29.401136Z", 
  "msg": [
   "For issue #3709 (\"Inconsistency between \"svn list\" and \"svn", 
   "checkout\"), ignore authz errors raised when recursing.", 
   "* subversion/libsvn_client/list.c", 
   "(get_dir_contents): Catch and ignore SVN_ERR_RA_NOT_AUTHORIZED and", 
   "SVN_ERR_RA_DAV_FORBIDDEN errors returned from the server."
  ], 
  "revision_id": "997471"
 }
]